# Numpy Introduction

In [1]:
import numpy

In [2]:
x = numpy.array([1,2,3,4,5,6,7,8,9])
print(x)



[1 2 3 4 5 6 7 8 9]


In [3]:
#create the arrays in the numpy 

In [4]:
x = numpy.array([1,2,3,4,5,6,7,8,9])
print(x)
y = numpy.array((1,2,3,4,5,6,7,8,9))
print(y)


[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


# Dimentional 

In [23]:
import numpy


#scalar dimentional array

x = numpy.array(45)
print(x.ndim)


#one dimentional array or uni-dimentional array


y = numpy.array([1,2,3,4,5,6,7,8,9])
print(y.ndim)


#two dimentional array 


z = numpy.array([[1,2],[8,2]])
print(z.ndim)


#three dimentional array or multi-dimentional array


z1 = numpy.array([[[1,4,5,6],[8,7,6,5],[8,7,6,5]]])
print(z1.ndim)




0
1
2
3


In [25]:
z2 = numpy.array([1,2,3,4,5],ndmin = 5)

print(z2)
print(z2.ndim)

[[[[[1 2 3 4 5]]]]]
5


# Indexing

In [26]:
#First Dimention Idexing

In [30]:
x = numpy.array([1,2,3,4,5,6,7,8,9])


print(x[0])
print(x[-1])

print(x[0],x[-1])

y=x[0]+x[-1]

print(y)


1
9
1 9
10


In [31]:
#Two Dimention Idexing

In [37]:
z = numpy.array([[1,2,3],[4,5,6]])

print(z)

print()

print(z[0])

print(z[0,0])

print(z[0,1])

print(z[1,0])

print(z[1,1])



[[1 2 3]
 [4 5 6]]

[1 2 3]
1
2
4
5


In [48]:
z1 = numpy.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])

print(z1[0])
print()

print(z1[0,0])
print()

print(z1[0,1])
print()

print(z1[0,1,1])
print()

print(z1[0,1,2])
print()

print(z1[0,-1])
print()

print(z1[0,-1,-1])
print()

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[1 2 3 4]

[5 6 7 8]

6

7

[ 9 10 11 12]

12



# Slicing in the Single Dimentional

In [53]:
x = numpy.array([1,2,3,4,5,6,7,8,9])


print(x[1:])

print()

print(x[3:5])

print()

print(x[-3:])

[2 3 4 5 6 7 8 9]

[4 5]

[7 8 9]


# Slicing in the Two Dimentional

In [61]:

z = numpy.array([[1,2,3,4,5,6],[1,2,2,3,4,5]])
print(z)

print()

print(z[0,1:])

print()

print(z[0,0:4])

print()

print(z[1,-1:])

[[1 2 3 4 5 6]
 [1 2 2 3 4 5]]

[2 3 4 5 6]

[1 2 3 4]

[5]
